name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with "v"

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4  # Add any other dependencies your project needs

      - name: Build Package
        run: |
          # Add your build commands here if needed, e.g., packaging your project
          echo "Building your package..."

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: |
            ./dist/*  # Adjust to your build output if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Release
        run: echo "Release created successfully!"
